### ISSUE TITLE
Установка на Windows без русского языка

### ISSUE THREAD

**Issue by kr0nic** [ProjectSoft-STUDIONIONS/radioappnwjs#1]
![Screenshot_1](https://user-images.githubusercontent.com/19549758/54281915-d2362a00-45ab-11e9-9953-4ec2ad34daf7.png)
![Screenshot_2](https://user-images.githubusercontent.com/19549758/54281918-d3675700-45ab-11e9-83e9-17689f6b5dc7.png)
![Screenshot_3](https://user-images.githubusercontent.com/19549758/54281957-ed089e80-45ab-11e9-9baa-c6954bac1f4a.png)

**Comment by ProjectSoft-STUDIONIONS** [comment]
Если устанавливать любую другую программу, которая создаёт ярлык на русском - то же самое?
Мне важно понять именно с системой. 
Саму установку пропустим, ибо крякозяблы даже в языке по дефолту.

**Comment by kr0nic** [comment]
> Если устанавливать любую другую программу, которая создаёт ярлык на русском - то же самое?

проверить не могу. не знаю даже какую программу можно взять за пример, которая полностью на русском, без поддержки английского. 

> Мне важно понять именно с системой.

Вот скрин из настроек. В _Windows display language_ есть только английский
![image](https://user-images.githubusercontent.com/19549758/54349138-a5d9e680-465b-11e9-9335-1afd8000bac5.png)

**Comment by ProjectSoft-STUDIONIONS** [comment]
Сейчас есть выбор языка. Русский/Английский.
