### ISSUE TITLE
Имя exe файла установщика

### ISSUE THREAD

**Issue by kr0nic** [ProjectSoft-STUDIONIONS/radioappnwjs#3]
Сейчас **YouRadio.exe** вместо **YourRadio.exe**. Пропущена **r**

И туда же к файлу установщика вот такой copyright сейчас 
![image](https://user-images.githubusercontent.com/19549758/54282507-34435f00-45ad-11e9-90d2-1711ee6c9825.png)
![image](https://user-images.githubusercontent.com/19549758/54282563-5210c400-45ad-11e9-836a-a50f11fa6619.png)

_2010_  год

**Comment by ProjectSoft-STUDIONIONS** [comment]
Изначально и было YouRadio.exe. Это я намудрил.

**Comment by ProjectSoft-STUDIONIONS** [comment]
Имя файла ни так важно.
