### ISSUE TITLE
Старт/Стоп в треe

### ISSUE THREAD

**Issue by kr0nic** [ProjectSoft-STUDIONIONS/radioappnwjs#4]
Хотелось бы иметь возможность Старт/Стоп в этом меню из трея. 
Чтобы не делать лишнего открытия приложения. 
![image](https://user-images.githubusercontent.com/19549758/54285805-b46cc300-45b3-11e9-9b4e-c1da507c05b4.png)

Еще как доп опцией было бы хорошо добавить старт-стоп фукнционал на двойной щелчок по  приложению в трее.

**Comment by ProjectSoft-STUDIONIONS** [comment]
Реализовано
